# action.yml
name: 'Terraform Quality Gate'
description: 'Lint, Static Analysis and Testing of Terraform code'
author: 'Dallin Wright'
branding:
  icon: 'award'
  color: 'purple'
inputs:
  terratest:
    description: 'Should include Terratests'
    required: true
  terraform_cloud_token:
    description: 'Terraform cloud token, if using Terraform cloud'
    required: false
  aws_access_key_id:
    description: 'AWS key id, if using AWS'
    required: false
  aws_secret_access_key:
    description: 'AWS access key, if using AWS'
    required: false
runs:
  using: 'docker'
  image: 'docker://docker.pkg.github.com/dallinwright/terraform_quality_gate/terraform_quality_gate:v0.0.3'
  args:
    - ${{ inputs.terratest }}
    - ${{ inputs.terraform_cloud_token}}
    - ${{ inputs.aws_access_key_id }}
    - ${{ inputs.aws_secret_access_key}}
