# action.yml
name: 'Terraform Quality Gate'
description: 'Lint, Static Analysis and Testing of Terraform code'
author: 'Dallin Wright'
branding:
  icon: 'award'
  color: 'purple'
inputs:
  terratest:
    description: 'Should include Terratests'
    required: false
    default: 'none'
runs:
  using: 'docker'
  image: 'docker://optionalpaca/terraform-quality-gate'
  args:
    - ${{ inputs.terratest }}
    - ${{ inputs.token}}
