name: 'Publish'

on:
  push:
    branches:
      - master

jobs:
  Build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build & Publish
        uses: docker/build-push-action@v1.1.0
        with:
          registry: https://docker.pkg.github.com
          repository: dallinwright/terraform_quality_gate
          tag_with_ref: true
          username: dallinwright
          password: ${{ secrets.GITHUB_TOKEN }}