name: 'Publish'

on:
  push:
    branches:
      - master

jobs:
  Build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: jerray/publish-docker-action@master
        with:
          registry: docker.pkg.github.com
          repository: dallinwright/terraform_quality_gate